ASSIGNEES = {
    'Abdo Elmi': 'AbdoElmis',
    'Brian': 'blsrsyd',
    'Rikke Jorgensen': 'BornholmsReg',
    'Camilla Graesborg': 'CamillaGraesborg-RegionSyddanmark',
    'Filip Bruman': 'COWI-FIBR',
    'Emil Sahin': 'emsi-cowi',
    'Eskild Laursen': 'eskildnilas',
    'Henriette Hillerup Larsen': 'Henrielregsj',
    'Helle': 'hjbrsyd',
    'Isabella Niekrenz': 'IsabellaRM',
    'Jacob': 'JacobWinde',
    'Jan': 'jasjni',
    'Jens': 'jenpetmidt',
    'Brian': 'JoachimMahrtNy',
    'John Ryan Pedersen': 'JohnRyanPedersen',
    'Julie Dohn': 'JulieDohn',
    'Kasper Witturl': 'kawije',
    'Kim Jacobsen': 'Kimjac58',
    'Krzysztof Kowalski': 'KPKowal',
    'Kristoffer Schroder': 'KristofferDS',
    'Lars Ernst': 'larern',
    'Lars Christensen': 'LarsTOAO',
    'Line Boel': 'lineboel',
    'Line Skovgaard': 'LineKyrsting',
    'Doesnt exist': 'LoRsj',
    'Mads Kjaer': 'Mads-RN',
    'Marianna Engberg Pedersen': 'maenpe',
    'Martin Holding': 'MartinHoldingRSYD',
    'Mia Louise Cramer Benner': 'MiaLCB',
    'Magnus Kilgour': 'midkrsyd',
}